export const translations = {
  en: {
    TextMenu:'Menu',
    lobbyMenuH2: 'Save Progress',
    lobbyMenuP: 'Sign up to save your progress or log into an existing account',
    SignUpBtn:'Sign up',
    SignInBtn: 'Sign in',
    SignInH3:'Sign in',
    forgotPassBtn: 'Forgot your Password?',
    H4SignVia:'Sign in via:',
    SignUpH3:'Sign up',
    H4WarnungPass:'Create a password 8-20 alphanumeric characters',
    SpanLabelAgree1:'I agree to the Privacy Policy ',
    SpanLabelAgree2:'and Terms of Service',
    btnSignUp:'Sign up',
    langBtnText:'EN',
    RulesSpan:'Rules',
    themeCardH3:'Background',
    ChangeAvatarLabel: 'Change',
    loginPlayerAkk:'Login:',
    EmailPlayerAkk:'E-Mail:',
    PassPlayerAkk:'Password:',
    changeNameLabel:'Change your Login',
    changeBtnLogin:'Change',
    OldPasswordLabel:'Old Password',
    NewPasswordLabel1:'New Password',
    NewPasswordLabel2: '(8-20 alphanumeric characters)',
    changeBtnPass:'Change',
    LogoutBtn:'Logout',
    DeleteP:'Delete Account?',
    DeleteBtn:'Delete',
    ButtonPlay:'Play Now',
  },

  ua: {
    TextMenu:'Меню',
    lobbyMenuH2: 'Зберегти прогрес',
    lobbyMenuP: 'Зареєструйтеся, щоб зберегти свій прогрес, або увійдіть до існуючого облікового запису',
    SignUpBtn:'Зареєструватися',
    SignInBtn: 'Увійти',
    SignInH3:'Увійти',
    forgotPassBtn: 'Забули пароль?',
    H4SignVia:'Увійти через:',
    SignUpH3:'Зареєструватися',
    H4WarnungPass:'Створіть пароль з 8-20 буквено-цифрових символів',
    SpanLabelAgree1:'Я погоджуюсь з Політикою конфіденційності',
    SpanLabelAgree2:'та Умовами використання',
    btnSignUp:'Зареєструватися',
    langBtnText:'UA',
    RulesSpan:'Правила',
    themeCardH3:'Фон',
    ChangeAvatarLabel: 'Змінити',
    loginPlayerAkk:'Логін:',
    EmailPlayerAkk:'Електронна пошта:',
    PassPlayerAkk:'Пароль:',
    changeNameLabel:'Змінити логін',
    changeBtnLogin:'Змінити',
    OldPasswordLabel:'Старий пароль',
    NewPasswordLabel1:'Новий пароль',
    NewPasswordLabel2:'(8-20 буквено-цифрових символів)',
    changeBtnPass:'Змінити',
    LogoutBtn:'Вийти',
    DeleteP:'Видалити обліковий запис?',
    DeleteBtn:'Видалити',
    ButtonPlay:'Грати зараз',
  },

  de: {
    TextMenu:'Menü',
    lobbyMenuH2:'Fortschritt speichern',
    lobbyMenuP: 'Registrieren Sie sich, um Ihren Fortschritt zu speichern, oder melden Sie sich bei einem bestehenden Konto an.',
    SignUpBtn:'Registrieren',
    SignInBtn: 'Anmelden',
    SignInH3:'Anmelden',
    forgotPassBtn: 'Passwort vergessen?',
    H4SignVia:'Anmelden über:',
    SignUpH3:'Registrieren',
    H4WarnungPass:'Erstellen Sie ein Passwort mit 8-20 alphanumerischen Zeichen',
    SpanLabelAgree1:'Ich stimme der Datenschutzerklärung zu',
    SpanLabelAgree2:'und den Nutzungsbedingungen',
    btnSignUp:'Registrieren',
    langBtnText:'DE',
    RulesSpan:'Regeln',
    themeCardH3:'Hintergrund',
    ChangeAvatarLabel: 'Ändern',
    loginPlayerAkk:'Login:',
    EmailPlayerAkk:'E-Mail:',
    PassPlayerAkk:'Passwort:',
    changeNameLabel:'Login ändern',
    changeBtnLogin:'Ändern',
    OldPasswordLabel:'Altes Passwort',
    NewPasswordLabel1:'Neues Passwort',
    NewPasswordLabel2:'(8-20 alphanumerische Zeichen)',
    changeBtnPass:'Ändern',
    LogoutBtn:'Abmelden',
    DeleteP:'Konto löschen?',
    DeleteBtn:'Löschen',
    ButtonPlay:'Jetzt spielen',
  }
}
