//позиции разных колючек
export const traps = [
  { x: 18, y: 11, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 15, y: 9, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 33, y: 5, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 29, y: 1, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 23, y: 1, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 8, y: 5, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 4, y: 13, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 22, y: 3, achse: 'up',     state: 'idle', timer: 0, didDamage: false  },
  { x: 19, y: 19, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 12, y: 19, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 10, y: 19, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 8, y: 19, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 25, y: 19, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 25, y: 9, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 20, y: 13, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 19, y: 7, achse: 'bottom',  state: 'idle', timer: 0, didDamage: false  },
  { x: 13, y: 17, achse: 'left', state: 'idle', timer: 0, didDamage: false },
  { x: 17, y: 16, achse: 'left',   state: 'idle', timer: 0, didDamage: false  },
  { x: 24, y: 14, achse: 'left',   state: 'idle', timer: 0, didDamage: false  },
  { x: 7, y: 10, achse: 'left',  state: 'idle', timer: 0, didDamage: false  },
  { x: 7, y: 13, achse: 'left',  state: 'idle', timer: 0, didDamage: false  },
  { x: 29, y: 16, achse: 'right',  state: 'idle', timer: 0, didDamage: false  },
  { x: 27, y: 10, achse: 'right',  state: 'idle', timer: 0, didDamage: false  },
  { x: 15, y: 15, achse: 'right',  state: 'idle', timer: 0, didDamage: false  },
  { x: 13, y: 11, achse: 'right',  state: 'idle', timer: 0, didDamage: false  },
  { x: 29, y: 5, achse: 'right',  state: 'idle', timer: 0, didDamage: false  },
  { x: 23, y: 8, achse: 'right',  state: 'idle', timer: 0, didDamage: false  },
];